title: Jeremy Chin's Corner
description: Hi, I'm Jeremy Chin—a software developer and engineering manager passionate about building thoughtful, scalable solutions. This site is where I share my journey in tech, from hands-on coding to leading development teams. Whether you're here to explore my past projects, read insights on software development, or just curious about what I'm working on, I'm glad you stopped by.

url: https://jeremychin.github.io
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    - title: Contact
      url: /contact

social:
    github: https://jeremychin.github.io    
    email: jeremy.chin@gmail.com
    linkedin: https://www.linkedin.com/in/chinjeremy/

# google_analytics: ""

# disqus:
#    shortname: brianmaierjr
